# Generated by Django 5.0.1 on 2024-01-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('carbohydrates', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('proteins', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('fats', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('calories', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('selectedGender', models.CharField(max_length=6)),
                ('basalMetabolicRate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('userImage', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
