# Generated by Django 5.0.1 on 2024-06-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_mealuser_meal_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='basaletabolic_rate',
            new_name='basal_metabolic_rate',
        ),
    ]
